platform :ios, '7.0'

target 'RLMObject-CopyingExample' do
  pod 'Realm', '2.8.1' # Xcode 9.0
  
  target 'RLMObject-CopyingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
